{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSConfiguration","text":"TSConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationInitCompletion","preciseIdentifier":"s:19TSAuthenticationSDK0A14InitCompletiona","text":"TSAuthenticationInitCompletion"},{"kind":"text","text":" = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication\/initialize(baseurl:clientid:configuration:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initialize(baseUrl:clientId:configuration:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a new WebAuthn SDK instance with your client context."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSConfiguration","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSAuthenticationInitCompletion","preciseIdentifier":"s:19TSAuthenticationSDK0A14InitCompletiona"},{"kind":"text","text":")"}],"title":"initialize(baseUrl:clientId:configuration:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:19TSAuthenticationSDK0A0C10initialize7baseUrl8clientId13configuration10completionySS_SSAA15TSConfigurationCSgyAA0A12InitResponse_pSg_AA0A5ErrorCSgtcSgtF","modules":[{"name":"TSAuthenticationSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"]]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"role":"symbol","title":"TSAuthentication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSAuthentication"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSAuthentication"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationInitCompletion":{"role":"symbol","title":"TSAuthenticationInitCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSAuthenticationInitCompletion"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationInitCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSAuthenticationInitCompletion"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthenticationinitcompletion"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/initialize(baseUrl:clientId:configuration:completion:)":{"role":"symbol","title":"initialize(baseUrl:clientId:configuration:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSConfiguration","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSAuthenticationInitCompletion","preciseIdentifier":"s:19TSAuthenticationSDK0A14InitCompletiona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new WebAuthn SDK instance with your client context."}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initialize(baseUrl:clientId:configuration:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/initialize(baseurl:clientid:configuration:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","type":"topic","url":"\/documentation\/tsauthenticationsdk"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSConfiguration":{"role":"symbol","title":"TSConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSConfiguration"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSConfiguration"}],"url":"\/documentation\/tsauthenticationsdk\/tsconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","value":"TSAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments","value":[{"kind":"identifier","text":"TSAuthentication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSConfiguration\/title","value":"TSConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSConfiguration\/fragments","value":[{"kind":"identifier","text":"TSConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}